name: autoUpdateMaster
on:
  push:
    branches:
      - master

jobs:
  trigger-curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: update-remote-master-branch
        env:
          DMC: ${{ secrets.dmc }}
          DMC_PARAM: dmc
        run: |
          curl --insecure --location --request GET 'https://159.75.167.202:38700/hook?access_key=${{ env.DMC }}&param=${{env.DMC_PARAM}}' \
          --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'