name: autoUpdateDev
on:
  push:
    branches:
      - dev

jobs:
  trigger-curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: update-remote-dev-branch
        env:
          KEY: ${{ secrets.dmc }}
          PRO_PARAM: dmc_dev
        run: |
          curl --insecure --location --request POST 'https://159.75.167.202:38700/hook' \
          --header 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
          --form 'access_key="${{ env.KEY }}"' \
          --form 'param="${{env.PRO_PARAM}}"'